### ISSUE TITLE
Problems starting a 1.12.2 modded server

### ISSUE THREAD

**Issue by SeaCrusher27** [MinecraftForge/Documentation#360]
It worked when i ran it on my pc but when i moved it to my server pc it didn't run and gave this error:

A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more

The server pc has java 6 u 281 64bit
If any more information is required i will be happy to give it.

**Comment by sciwhiz12** [comment]
1.12 is no longer supported by Forge.
Also, this is the wrong repository (this is for the official Forge documentation). In the future, please use the [Forge Support Forums](https://forums.minecraftforge.net/) for asking help for _supported_ versions.
